services:
  - type: web
    name: forex-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8448863022:AAG1u9aCnHoKlDam4Go_N_IBbcFv4KHLG8c  # REPLACE WITH ACTUAL TOKEN
